#!/usr/bin/env bash
# Configure Nginx server to redirect /redirect_me to another page.
MESSAGE="Hello World!"
LOCATION="\n\tlocation /redirect_me {\n\t\treturn 301 https://youtu.be/dQw4w9WgXcQ; \n\t}\n"
FILE="/etc/nginx/sites-available/default"
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "$MESSAGE" > /var/www/html/index.nginx-debian.html
sed -i "37i\ $LOCATION" "$FILE"
service nginx restart
