#!/usr/bin/env bash
# Installs HAProxy and configure it on lb-01 server

apt-get -y update && apt-get -y install haproxy

printf %s "
global
    log 127.0.0.1 local0 notice
    user haproxy
    group haproxy
defaults
    log     global
    mode    http
    option  httplog
    option redispatch
listen hbnb
    bind 0.0.0.0:80
    mode http
    balance roundrobin
    cookie SERVERUSED insert indirect nocache
    server 4639-web-01 44.210.240.112:80 check cookie 4639-web-01
    server 4639-web-02 3.236.52.142:80 check cookie 4639-web-02
" >> /etc/haproxy/haproxy.cfg

echo "ENABLED=1" >> /etc/default/haproxy
service haproxy start
