#!/usr/bin/env bash
# Displays numbers from 1 to 20 but "bad luck from ..." on 4th, 9th and 17th iterations
n=1

while [ $n -le 20 ]
do
    echo $n
    case $n in
        4)
            echo "bad luck from China"
            ;;
        9)
            echo "bad luck from Japan"
            ;;
        17)
            echo "bad luck from Italy"
            ;;
        *)
            ;;
    esac
    n=$(( n + 1 ))
done;
