#!/usr/bin/env bash
#Configures the server's firewall to block all incoming traffic
#Only allow TCP ports 22, 80 and 443
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp
ufw allow 80/tcp
ufw allow 443/tcp
